#!/bin/bash

if ! options=$(getopt -l name:,delay:,jitter: -- "$@"); then
    exit 1
fi

set -- $options

name=".*"
delay="100ms"
jitter="10ms"

while [ $# -gt 0 ]; do
    case $1 in
    --name|--delay|--jitter)
        declare "${1#--}"="$2"
        shift
        ;;
    --)
        shift
        break
        ;;
    -*)
        echo "$0: error - unrecognized option $1" >&2
        exit 1
        ;;
    *) break ;;
    esac
    shift
done

get_ifaces() {
    bash /usr/bin/dockerveth.sh |
        mlr --tsv --headerless-csv-output \
            filter "\$VETH != \"not_found\"" then \
            filter "\$NAMES =~ \"$name\"" then \
            cut -f VETH
}

update_netem () {
    for iface in $(get_ifaces); do
        echo "Applying delay $delay, jitter $jitter on $iface"
    done
}

update_netem
